### ISSUE TITLE
リポジトリのルート以外でのコンパイルができなくなった

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#268]
たとえばカレントディレクトリが `sample/aplusb` の状態で `python3 ../generate.py info.toml` をするなどです。以前は動いていたのですが、動かなくなりました。

online-judge-tools からはそのようにして呼び出している (chdir すると面倒が増える) ので、これが動かないのは困ります。

``` console
$ pwd
/home/ubuntu/.cache/online-judge-tools/library-checker-problems/sample/aplusb
$ python3 ../../generate.py info.toml
2020-02-07 03:41:27,635 INFO __main__ : Start
2020-02-07 03:41:27,636 INFO __main__ : generate params.h
2020-02-07 03:41:27,636 INFO __main__ : compile solution
2020-02-07 03:41:28,029 INFO __main__ : compile generators
2020-02-07 03:41:28,030 INFO __main__ : compile example.in
2020-02-07 03:41:28,030 INFO __main__ : compile random.cpp
gen/random.cpp:3:10: fatal error: random.h: No such file or directory
 #include "random.h"
          ^~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "../../generate.py", line 445, in <module>
    Path(args.htmldir) if args.htmldir else None)
  File "../../generate.py", line 357, in generate
    problem.compile_gens()
  File "../../generate.py", line 130, in compile_gens
    compile(self.basedir / 'gen' / name, self.libdir)
  File "../../generate.py", line 43, in compile
    ['-o', str(src.with_suffix(''))] + [str(src)])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '-O2', '-std=c++14', '-Wall', '-Wextra', '-Werror', '-Wno-unused-result', '-I', '/home/ubuntu/.cache/online-judge-tools/library-checker-problems/sample/aplusb/common', '-o', 'gen/random', 'gen/random.cpp']' returned non-zero exit status 1.
```

**Comment by kmyk** [comment]
ref https://github.com/kmyk/online-judge-verify-helper/pull/125 https://github.com/kmyk/online-judge-verify-helper/pull/126 https://github.com/kmyk/online-judge-verify-helper/pull/127

**Comment by beet-aizu** [comment]
これはoj側で呼んでいてojよりはこっちの方がマージされるまでの時間が短いのでこっちを修正した方がいいということでしょうか　（ここですかね　https://github.com/kmyk/online-judge-tools/blob/7c9340d1cc73748d64d87350f110cac480af7474/onlinejudge/service/library_checker.py#L100

**Comment by beet-aizu** [comment]
https://github.com/yosupo06/library-checker-problems/blob/e652db0d834115c496303cac2e98110c637c931c/generate.py#L414　ここをいい感じにできればいいんですけど、いい感じって何だよ

**Comment by kmyk** [comment]
いい感じ (`libdir` を `generate.py` の親ディレクトリにする)

**Comment by yosupo06** [comment]
今まではproblems.tomlがリポジトリルートへのアンカーの役割を果たしていたんですが、problems.tomlを消したのでこれが起きたということですね

**Comment by yosupo06** [comment]
これまだ死んでました

**Comment by kmyk** [comment]
https://github.com/kmyk/online-judge-tools/pull/671 は動いてます。deprecated になった旧形式の指定がだめぽい

``` console
$ python3 ~/.cache/online-judge-tools/library-checker-problems/generate.py ~/.cache/online-judge-tools/library-checker-problems/problems.toml -p aplusb
2020-02-07 22:23:44,318 WARNING __main__ : problems.toml is deprecated
2020-02-07 22:23:53,324 ERROR __main__ : Cannot find problem: aplusb
```

**Comment by yosupo06** [comment]
```-p unionfind``` は使うかなと思って残しておいたんでした(IDから実際のinfoを探すのは少し手間なので)

**Comment by beet-aizu** [comment]
はい　https://github.com/yosupo06/library-checker-problems/pull/271#issue-372413881

**Comment by kmyk** [comment]
直った
